name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
    - "v*.*.*"
concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}

jobs:
  build-windows-x64:
    runs-on: windows-2022
    env:
      Artifact: worldtree-sdk-${{ github.ref_name }}-windows-x64.zip
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: engine/package.json
    - working-directory: engine
      run: |
        pnpm install
    - working-directory: engine/standalone/browser
      run: |
        pnpm run build
    - working-directory: cli
      run: |
        cargo build --release
        cargo install cargo-about
        cargo about generate -o target\release\THIRD-PARTY about.hbs
    - working-directory: cli/target/release
      run: |
        7z a ..\..\..\${Env:Artifact} worldtree.exe
        7z a ..\..\..\${Env:Artifact} THIRD-PARTY
    - run: |
        7z a ${Env:Artifact} LICENSE
    - uses: actions/upload-artifact@v4
      with:
        name: windows-x64
        path: ${{ env.Artifact }}
  
  build-macos-x64:
    runs-on: macos-13
    env:
      ARTIFACT: worldtree-sdk-${{ github.ref_name }}-macos-x64.zip
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: engine/package.json
    - working-directory: engine
      run: |
        pnpm install
    - working-directory: engine/standalone/browser
      run: |
        pnpm run build
    - working-directory: cli
      run: |
        cargo build --release
        cargo install cargo-about
        cargo about generate -o target/release/THIRD-PARTY about.hbs
    - working-directory: cli/target/release
      run: |
        7z a ../../../${ARTIFACT} worldtree
        7z a ../../../${ARTIFACT} THIRD-PARTY
    - run: |
        7z a ${ARTIFACT} LICENSE
    - uses: actions/upload-artifact@v4
      with:
        name: macos-x64
        path: ${{ env.ARTIFACT }}

  build-macos-arm64:
    runs-on: macos-14
    env:
      ARTIFACT: worldtree-sdk-${{ github.ref_name }}-macos-arm64.zip
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: engine/package.json
    - working-directory: engine
      run: |
        pnpm install
    - working-directory: engine/standalone/browser
      run: |
        pnpm run build
    - working-directory: cli
      run: |
        cargo build --release
        cargo install cargo-about
        cargo about generate -o target/release/THIRD-PARTY about.hbs
    - working-directory: cli/target/release
      run: |
        7z a ../../../${ARTIFACT} worldtree
        7z a ../../../${ARTIFACT} THIRD-PARTY
    - run: |
        7z a ${ARTIFACT} LICENSE
    - uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: ${{ env.ARTIFACT }}

  build-linux-x64:
    runs-on: ubuntu-22.04
    env:
      ARTIFACT: worldtree-sdk-${{ github.ref_name }}-linux-x64.zip
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: engine/package.json
    - working-directory: engine
      run: |
        pnpm install
    - working-directory: engine/standalone/browser
      run: |
        pnpm run build
    - working-directory: cli
      run: |
        cargo build --release
        cargo install cargo-about
        cargo about generate -o target/release/THIRD-PARTY about.hbs
    - working-directory: cli/target/release
      run: |
        zip ../../../${ARTIFACT} worldtree
        zip ../../../${ARTIFACT} THIRD-PARTY
    - run: |
        zip ${ARTIFACT} LICENSE
    - uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: ${{ env.ARTIFACT }}
